### ISSUE TITLE
Neato Botvac D5

### ISSUE THREAD

**Issue by lolfr** [naofireblade/homebridge-neato#1]
Hello,

I recently install your plug-in, to integrate my Botvac D5 to my homeKit scenes. However, if the plug-in seems to works, and the accessory appear in my Home App, there are two switchs wich appear for the Neato and none of them seems to works. I can activate any of them, but the Neato doesn't move.
In the same time, the Dock detector seems to works perfectly.

How can I help you to debug it ?

Best regards,

**Comment by naofireblade** [comment]
Hello lolfr,

thank you for posting here. I appreciate that. First of all, please make sure you use the latest version 0.3.0 of the plugin that i published 4 days ago.
What App do you use for homekit? Can you try "Elgato Eve"? You should see 4 switches, the dock state and battery state. Do you see all that?

![img_0106](https://cloud.githubusercontent.com/assets/12081369/26172098/77ef0ffa-3b47-11e7-8684-6f46d3d31e19.PNG)

It would be really helpful if you could start your homebridge with the debug command for my plugin (just change the path to your directory):
`sudo DEBUG=homebridge-neato homebridge -U /var/lib/homebridge`

Then please check the console output for messages from the robot. Like this:

> [5/17/2017, 7:14:23 PM] [Sam] Found robot: Sam

There will also be an output of all available commands for the robot (some null). Ignore that for now. Set the switch for "Go To Dock" to off and the available commands will be output in the console again (all true or false). That should look like this:

>   homebridge-neato Robot {
>   homebridge-neato   _baseUrl: 'https://nucleo.neatocloud.com/vendors/neato/robots/',
>   homebridge-neato   name: 'Sam',
>   homebridge-neato   _serial: '',
>   homebridge-neato   _secret: '',
>   homebridge-neato   eco: false,
>   homebridge-neato   spotWidth: 100,
>   homebridge-neato   spotHeight: 100,
>   homebridge-neato   spotRepeat: false,
>   homebridge-neato   isCharging: false,
>   homebridge-neato   isDocked: true,
>   homebridge-neato   isScheduleEnabled: false,
>   homebridge-neato   dockHasBeenSeen: false,
>   homebridge-neato   charge: 98,
>   homebridge-neato   canStart: true,
>   homebridge-neato   canStop: false,
>   homebridge-neato   canPause: false,
>   homebridge-neato   canResume: false,
>   homebridge-neato   canGoToBase: false } +880ms

Can you paste that here? But please **REMOVE YOUR SERIAL AND SECRET** before pasting, otherwise i might clean your house :) .

Best wishes
Arne

**Comment by naofireblade** [comment]
Another question. Does an exclamation mark occur when you try to start cleaning with the Eve App? Can you enable and disable the schedule and does it change properly on the robot?

**Comment by naofireblade** [comment]
Hey, you might not need to debug. I checked the neato docs and created a pull request for the underlying neato node which the creator instantly published. So after an update to 0.3.1 the plugin should work with your D5 now. Just run `sudo npm update -g homebridge-neato`

**Comment by lolfr** [comment]
Whoa 😲 you're fast.  

I'll have plan to do the test this weekend. But in the meantime I have to debug my system, because I installed a bunch of plug-ins for homebridge and now it's quit inexplicably really often.  

I'll check this and keep you in touch.  
Laurent

**Comment by lolfr** [comment]
So I do the update and it's works fine now.  

Next step for me is to create scripts. 😁  

Thanksgiving a lot for the terrific job !! 👍👍👍

**Comment by naofireblade** [comment]
Great to hear that. Thanks for your feedback.

**Comment by naofireblade** [comment]
Yes, i updated the plugin meanwhile to support multiple robots at once. You have to put your config now into "platforms". In the readme is an example for the new config.

**Comment by lolfr** [comment]
Damn… I knew i would have to read the readme file… always RTFM !! 😅  

Sorry, and thanks again for your terrific work.  

Cheers
