### ISSUE TITLE
return to dock parameter

### ISSUE THREAD

**Issue by andyzeo** [naofireblade/homebridge-neato#15]
is the dock parameter/switch made to call the function to return to dock? if so it should be a press-release switch, that calls the function and return to the inactive state, no? instead is it configured with an on-off that has not much sense for an on-state  after the bot is back to dock.

or is it made to prevent the robot from returning to dock? if so, refining documentation is required.

otherwise, the plugin is amazing, if only a bit more responsive for the stopping commands while the robot is busy.

congrats and I hope it helps.

**Comment by naofireblade** [comment]
Hello @andyzeo 

Thanks for your advice. Sadly homekit does not allow disabling buttons (there is a spec for that but this gives errors in the ui). So i use the "On" state do *disable* the button. When the robot can't go home (because its docked, already returning home or does not know where is station is) the button will be "On". As soon as the robot is able to go home, the button will be *enabled* and switched to "Off".

I will add this to the documentation on the next update.
